name: movies_series_app
description: "Movies and series app to Rappipay tech."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  equatable: ^2.0.7
  either_dart: ^1.0.0
  flutter_riverpod: ^2.6.1
  http: ^1.3.0
  flutter_native_splash: ^2.4.4
  mockito: ^5.4.5
  cupertino_icons: ^1.0.8
  freezed: ^2.5.8
  card_swiper: ^3.0.1
  freezed_annotation: ^2.4.4
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  json_serializable: ^6.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
